name: Prettier
on:
  push:
    branches:
      - '**'

jobs:
  prettier:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Prettier and plugins
        run: npm install --save-dev prettier prettier-plugin-astro

      - name: Run Prettier
        run: npx prettier --write .

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'style: format codebase with prettier'
          title: 'Style: Code Formatting Updates'
          body: |
            ## ✨ Automated Code Formatting

            This PR contains code formatting changes made by Prettier to maintain consistent code style across the project.

            ### 🔍 Changes Include:
            - Consistent indentation
            - Standardized quote usage
            - Proper spacing
            - Organized imports
            - Uniform line endings

            ### 🤖 Auto-generated by:
            - Prettier
            - GitHub Actions

            > 📝 Note: This is an automated PR. Please review the changes before merging.
          branch: prettier-formatting
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
