name: Prettier Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*"
          only_changed: true
          commit_message: "chore: format code with Prettier"
