name: Prettier Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      workflows: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          only_changed: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "style: format code with Prettier"
