name: Prettier
on: [push]

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: bahmutov/npm-install@v1
      
      - name: Run Prettier
        run: npm run format
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'style: format with prettier'
          title: 'style: format code with prettier'
          body: 'Automated PR to fix code formatting using Prettier'
          branch: prettier-fixes
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}