name: Code Formatting with Prettier
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]

jobs:
  prettier:
    name: Format Code
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install project dependencies
        run: npm install

      - name: Run Prettier formatting
        if: github.event_name == 'push'
        run: npm run format

      - name: Create automated PR
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'style: format codebase with prettier'
          title: 'Style: Code Formatting Updates'
          body: |
           ✨ This PR automatically formats the codebase using Prettier.
            
            - Ensures consistent code style
            - Improves code readability
            - Maintains project formatting standards
          branch: prettier-formatting
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          git push origin --delete prettier-formatting || true